### ISSUE TITLE
Try to use the new write-dts mode from fork-ts-checker-webpack-plugin

### ISSUE THREAD

**Issue by onigoetz** [swissquote/crafty#1356]
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/679

**Comment by PierBJX** [comment]
@onigoetz Did you succeed to use the new mode `write-dts` ?

**Comment by PierBJX** [comment]
I create a [repo](https://github.com/PierBJX/fluffy-enigma/tree/main/webpack/fork-ts-checker) with `write-dts` mode and it does not work.
