### ISSUE TITLE
Eslint rule "@swissquote/swissquote/import/no-restricted-paths" doesn't work with TSconfig "paths" aliases

### ISSUE THREAD

**Issue by mindhalt** [swissquote/crafty#2066]
Crafty loads wrong parser for TS files, thus it completely ignore aliased `paths` in `tsconfig.json`.
 
Correct parser is present in `package.json` (https://github.com/swissquote/crafty/blob/master/packages/eslint-plugin-swissquote/package.json#L36) and should be configured somewhere here: https://github.com/swissquote/crafty/blob/master/packages/eslint-plugin-swissquote/index.js
But for some reason it doesn't work (probably configuration got outdated on deps version bump or something similar).
When debugging, this this is `undefined`:
![screenshot](https://github.com/swissquote/crafty/assets/517798/b755dbb3-5351-493d-8d9b-1025247e8a78)

**Comment by onigoetz** [comment]
Released Released in https://github.com/swissquote/crafty/releases/tag/v1.25.0
