### ISSUE TITLE
"Error: act(...) is not supported in production builds of React" with jest.config.mjs generated by crafty v1.24.0

### ISSUE THREAD

**Issue by denuko** [swissquote/crafty#2281]
Hello! After upgrading to crafty v1.24.0 and generating files with `crafty ide`, the following issue is happening specifically with jest.config.mjs:

After generating and using the _jest.config.mjs_ in IntelliJ integrated test run, the following error occurs
```
Error: act(...) is not supported in production builds of React.
 
    at Object.<anonymous>.exports.unstable_act (/home/dkasidia/workspace/securities-retail-paid-prices-plugin/server-war/src/main/frontend/node_modules/react/cjs/react.production.min.js:23:393)
```
 
I reproduced that with crafty v1.24.0 and the newly generated jest.config.mjs. The test run was working fine with previous jest.config.js (generated by older crafty version).

I tried to add NODE_ENV=test in the configuration so that it's appended to the jest command, but it was not effective.
![MicrosoftTeams-image (27)](https://github.com/swissquote/crafty/assets/4276197/132a8223-a1f5-4eab-8d11-b6c1fa922d6c)

 
I did some console.log in jest.config.mjs to check NODE_ENV. Initially it's test, then changes to production after initialize()
![MicrosoftTeams-image (28)](https://github.com/swissquote/crafty/assets/4276197/9d066c5f-e40d-47d5-9a04-fcba91f6907f)

Could you please look into that? Thanks!

**Comment by onigoetz** [comment]
Hi, thanks for the report

Crafty needs to set the environment variable for builds, and indeed, tests have different needs than builds.

I hardcoded 
```
// Crafty configures its own environment for builds
// tests have different needs
process.env.NODE_ENV = "test";
```

right after `initialize`
I will release this soon but you can add it to your file in the meantime

**Comment by onigoetz** [comment]
Released Released in https://github.com/swissquote/crafty/releases/tag/v1.25.0

**Comment by denuko** [comment]
I tried the new release and it works great! Thanks a lot!

**Comment by onigoetz** [comment]
awesome, happy it works :)
