### ISSUE TITLE
Problem overriding linter configuration.

### ISSUE THREAD

**Issue by partizanos** [swissquote/crafty#381]
Hello in the latest version of crafty (1.7.1) there is some issue with overriding linting rules, even after running the autofix command:

`npx crafty jsLint js/**/*.tsx js/**/*.ts --fix`

What we tried:
The `overrides`  configuration is not taken into account, for all the 3 different ways .  

**1st way** 

`eslint: {
    rules: {
      "@swissquote/swissquote/import/prefer-default-export": "warn"
    },
    overrides: {
      files: ["*.ts", "*.tsx"],
      rules: {
        "@swissquote/swissquote/@typescript-eslint/no-unused-vars": [
          "warn",
          {args: "none", vars: "local", ignoreRestSiblings: true}
        ],
        "@swissquote/swissquote/@typescript-eslint/no-use-before-define": "warn"
      }
    }
  }`

**2nd way** 

` eslint: {
    rules: {
      "@swissquote/swissquote/import/prefer-default-export": "warn",
      "@swissquote/swissquote/@typescript-eslint/no-use-before-define": "warn"
    }
  },`

**3rd way**

eslint: {
    rules: {
      "@swissquote/swissquote/import/prefer-default-export": "warn",
      "@swissquote/swissquote/@typescript-eslint/no-unused-vars": [
        "error",
        { args: "none", vars: "local", ignoreRestSiblings: true }
      ],
      "@swissquote/swissquote/@typescript-eslint/no-use-before-define": "warn"
    }`

Maybe a helpful observation: 
In the modules `@swissquote.eslint-plugin-swissquote/index.js` module there is an `overrides` object already hardcoded, so I think there is problem overriding this one.

**Comment by onigoetz** [comment]
Upon research it seems it’s a problem that comes from ESLint : https://github.com/eslint/eslint/issues/11510

It will be fixed in ESLint 6.0

**Comment by onigoetz** [comment]
This was actually fixed in 1.8.0
